# 配置服务端口号
server:
  port: 10800

logging:
  file:
    name: D://logs/service-cart/info.log
spring:
  redis:
    host: 192.168.100.50
    port: 6379
    password: 123456
  main:
    allow-bean-definition-overriding: true

