# 配置服务端口号
server:
  port: 10400

# 配置canal的服务端地址

logging:
  file:
    name: D://logs/service-canal/info.log
        
canal:
  client:
    instances:
      example:
        host: 192.168.100.50
        port: 11111
spring:
  redis:
    host: 192.168.100.50
    port: 6379
    password: 123456