# 配置服务端口号
server:
  port: 10300

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.100.50
    port: 6379
    password: 123456

logging:
  file:
    name: D://logs/service-item/info.log

