# 配置服务端口号
server:
  port: 10100

# 配置数据库的连接信息
spring:
  profiles:
    include: shardingsphere
  redis:
    host: 192.168.100.50
    port: 6379
    password: 123456
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://192.168.100.50:3306/gmall_product?useSSL=false&characterEncoding=UTF8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456

# 配置Redis的连接信息

# mybatis plus的相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.gmall.product.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 定义minio所需要的配置信息
gmall:
  minio:
    endpoint: http://192.168.100.50:9000
    accessKey: admin
    secretKey: admin123456
    bucket: gmall

# 配置日志文件的路径
logging:
  file:
    name: D://logs/service-product/info.log
