# shardingsphere的相关配置
# 1、数据源的配置
spring:
  shardingsphere:
    datasource:
      names: master,slave01,slave02
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.136.145:3306/gmall_product?useSSL=false&characterEncoding=UTF8
        username: root
        password: 1234
      slave01:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.136.145:3307/gmall_product?useSSL=false&characterEncoding=UTF8
        username: root
        password: 1234
      slave02:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.136.145:3308/gmall_product?useSSL=false&characterEncoding=UTF8
        username: root
        password: 1234
    rules:   # 2、读写分离的配置
      readwrite-splitting:
        data-sources:
          product-rw-rules:
            type: Static
            props:
              write-data-source-name: master
              read-data-source-names: slave01,slave02
            loadBalancerName: product_lb
        load-balancers:
          product_lb:
            type: ROUND_ROBIN
    props:
      sql-show: true

